### PR TITLE
Updated variable reference section i53

### PR DESCRIPTION
**Pull request by kerimoyle**
For discussion around #53 ... I've had a first go at rewording section C5. I'm not sure it's any clearer though! Please emend as needed.

### CODE REVIEW

**Comment by nickerso** [comment]
I think worth keeping in mind that this source was generated from the google doc via a complicated process :) I agree worth thinking about formatting going forward to make it easy to see what is changing and should make an issue for that.

**Comment by agarny** [comment]
> Thanks for taking the first go at this @kerimoyle. I personally find the revised version more confusing :) but it is also incorrect (e.g., a `math` element will never have a variable reference). I'll see if I can come up with an alternate revision.

See issue #72.

**Comment by kerimoyle** [comment]
> (e.g., a `math` element will never have a variable reference). 

This is what I was talking about yesterday ... What *is* a variable reference then?  I (clearly) don't even know ... I thought it included the variable name between the <ci> tags? otherwise how is it needed in the maths blocks (see conversation [here](https://github.com/cellml/cellml-specification/issues/53#issuecomment-598590552)? )

**Comment by kerimoyle** [comment]
> since we are "starting" work on this repo

@agarny ... while you might be "starting" ... others have been working for a month and hope to be "finishing" pretty soon! :)

**Comment by agarny** [comment]
> > since we are "starting" work on this repo
> 
> @agarny ... while you might be "starting" ... others have been working for a month and hope to be "finishing" pretty soon! :)

One month is nothing considering that CellML has been around for 20 years. That was my point. :)

**Comment by kerimoyle** [comment]
> Thanks for taking the first go at this @kerimoyle. I personally find the revised version more confusing :) but it is also incorrect (e.g., a math element will never have a variable reference). I'll see if I can come up with an alternate revision.

Ping @nickerso  ... thoughts on revision?

**Pull request closed without merging**
