### PR TITLE
I282 table numbers

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #282 

Manually added table numbers throughout the text to the links because numref can't do it for us.

Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i282_table_numbers/index.html

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Any way we could use this kind of construct to avoid the hard links?
```
.. table:: Table caption
   :name: table_x

:numref:`Table %s: Unit thingies<table_x>`
```
Found this online: https://github.com/sphinx-doc/sphinx/issues/1763

**Comment by kerimoyle** [comment]
Thanks, I'll give it a go (didn't even realise that "table" was a thing, oops!)

**Comment by MichaelClerx** [comment]
Me neither :D 
https://docutils.sourceforge.io/docs/ref/rst/directives.html#table

**Comment by MichaelClerx** [comment]
Looks good, but doesn't work for me in the PDF somehow. I'm not seeing the table heading anymore

**Comment by kerimoyle** [comment]
image it's not working at all ... yet ...

**Comment by agarny** [comment]
Ok, ping us when it's ready to review.

**Comment by MichaelClerx** [comment]
I've been playing around too and can't get it to work

**Comment by MichaelClerx** [comment]
Heyyyy that seems to work!

**Comment by kerimoyle** [comment]
Yep, getting there ... now I need to clean it up a little ...

**Comment by agarny** [comment]
Not quite working for me:
Screen Shot 2020-04-17 at 11 12 31 AM
Also, I would expect references to a table to read something like "Table x.y", not "Table x.y: some description" as is currently the case, e.g.:
Screen Shot 2020-04-17 at 11 14 02 AM

**Comment by kerimoyle** [comment]
I think it's nice to have the title of the table there ... since hoverxref doesn't seem to play nicely with it, it saves people from having to click on the link to find out which table it's talking about.  And it's (here's that magic word) consistent with our other internal links to sections and their titles ... ?

**Comment by agarny** [comment]
It's a personal preference of mine, but if the majority is in favour of keeping things as they are, then I am "fine".

**Comment by hsorby** [comment]
numref can do this see #285.

**Comment by kerimoyle** [comment]
yep, just fixing it up now @hsorby

**Comment by hsorby** [comment]
Already done in #285

**Pull request closed without merging**
