### PR TITLE
One sentence per line formatting

### PR DESCRIPTION
**Pull request by MichaelClerx**
Trying out #72

### CODE REVIEW

**Comment by kerimoyle** [comment]
Wow, that was fast :) Go you!

**Comment by kerimoyle** [comment]
@agarny .. does this work for you? If so, I need it in asap so that I can keep working ... :)

**Comment by kerimoyle** [comment]
https://cellml-specification-dev.readthedocs.io/en/72-one-line-formatting/
Looks fine to me :)

**Comment by MichaelClerx** [comment]
Thanks for merging @kerimoyle !

**Pull request merged**
