### PR TITLE
Using the power of numref.

### PR DESCRIPTION
**Pull request by hsorby**
Looking at fixing #282. and #278 

(As well as fixing some build warnings.)

### CODE REVIEW

**Comment by kerimoyle** [comment]
It would be really rather nice to know when we're working on parallel things so that we don't end up wasting time duplicating stuff ... yep, I am grumpy because today is meant to be my day off ... so - even more than usual - I don't want to spend it on wasted work!

**Comment by hsorby** [comment]
An issue with people rushing around trying to get last minute fixes in, sorry didn't realise that you were working on this.  It was one of those see it fix things.

**Comment by MichaelClerx** [comment]
The HTML version looks great, but this breaks the PDF build for me:

```
Exception occurred:
  File "/usr/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2050, in visit_number_reference
    number='\\ref{%s}' % self.idescape(id))
IndexError: tuple index out of range
The full traceback has been saved in /tmp/sphinx-err-9n5zcv3i.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:106: latexpdf] Error 2
```

**Comment by hsorby** [comment]
Damn, I don't have this error when running `make latexpdf`.

**Comment by hsorby** [comment]
Is there anything interesting in the log?

**Comment by agarny** [comment]
`make latexpdf` also works fine for me using Sphinx 2.4.0. @MichaelClerx, I believe you are using an older version? Could that be the reason?

**Comment by MichaelClerx** [comment]
Here's the log:

```
# Sphinx version: 1.8.4
# Python version: 3.7.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   reference/formal_and_informative/specC06_interpretation_of_initial_values
#   reference/formal_and_informative/specC07_effect_of_units_on_variables
#   reference/formal_and_informative/specC08_interpretation_of_mathematics
#   reference/formal_and_informative/specC09_interpretation_of_encapsulation
#   reference/formal_and_informative/specC10_interpretation_of_map_variables
#   reference/formal_and_informative/specC11_interpretation_of_variable_resets
#   reference/index_sectionD
#   
#   resolving references...
#   writing...
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.4) from /usr/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /usr/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.4) from /usr/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.todo (1.8.4) from /usr/lib/python3.7/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (1.8.4) from /usr/lib/python3.7/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.extlinks (1.8.4) from /usr/lib/python3.7/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.intersphinx (1.8.4) from /usr/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   hoverxref.extension (0.1b1) from /usr/local/lib/python3.7/site-packages/hoverxref/extension.py
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 220, in write
    docwriter.write(doctree, destination)
  File "/usr/lib/python3.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.7/site-packages/sphinx/writers/latex.py", line 204, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 10 more times]
  File "/usr/lib/python3.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/lib/python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.7/site-packages/sphinx/writers/latex.py", line 2050, in visit_number_reference
    number='\\ref{%s}' % self.idescape(id))
IndexError: tuple index out of range
```

**Comment by MichaelClerx** [comment]
Trying with sphinx 2.4 in a virtualenv, that gives me:

```
(venv) [michael@localhost specification]$ make html
sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v2.4.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/michael/dev/cellml/specification/venv/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/michael/dev/cellml/specification/venv/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/michael/dev/cellml/specification/src/conf.py", line 66, in <module>
    manage_index('in')
  File "/home/michael/dev/cellml/specification/src/conf.py", line 36, in manage_index
    os.rename(os.path.abspath(files[0]), os.path.abspath(files[1]))
FileNotFoundError: [Errno 2] No such file or directory: '/home/michael/dev/cellml/specification/src/master_index.rst' -> '/home/michael/dev/cellml/specification/src/index.rst'

make: *** [Makefile:45: html] Error 2
```

**Comment by hsorby** [comment]
If you hit an error with the configuration of the documentation.  You will have to undo the file move:
```
mv /home/michael/dev/cellml/specification/src/index.rst /home/michael/dev/cellml/specification/src/master_index.rst
```

and then re-run the config.

**Comment by MichaelClerx** [comment]
Thanks! That leads me to
```
sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v2.4.4
WARNING: hoverxref extension is not fully configured. Set hoverxref_project and hoverxref_version in your conf.py file.

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
make: *** [Makefile:45: html] Error 2
```

**Comment by kerimoyle** [comment]
Did you install the stuff from the requirements file?

**Comment by MichaelClerx** [comment]
Yeah. It's only sphinx-hoverxref in there

**Comment by MichaelClerx** [comment]
Now I'm getting somewhere with the pdf, but it won't compile :roll_eyes: 

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "FreeSerif" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

**Comment by agarny** [comment]
I think it might be directly related to LaTeX. I pretty much installed all of it and I seem to remember that @hsorby mentioned that he also had to install certain fonts.

**Pull request merged**
