### PR TITLE
i214 fix external links

### PR DESCRIPTION
**Pull request by kerimoyle**
Addresses #214 

Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i214_external_links/

Still required: 
- [x] Real address for PDF?
- [x] Real address for informative spec?
- [x] Decision as to which versions of URLs to display/link to (dated or not)

### CODE REVIEW

**Comment by kerimoyle** [comment]
I'm not superconfident that I'll build the PDF correctly ... please can someone check that the preamble links appear as you'd expect? (They may not be the correct addresses at the minute, but they should at least be rendered correctly).
Other than that, the references through the text should be correct now, as should the Reference section at the end.

**Comment by agarny** [comment]
> I'm not superconfident that I'll build the PDF correctly ... please can someone check that the preamble links appear as you'd expect? (They may not be the correct addresses at the minute, but they should at least be rendered correctly).
> Other than that, the references through the text should be correct now, as should the Reference section at the end.

Here is the [PDF file](https://github.com/cellml/cellml-specification/files/4484842/cellml2_specification.pdf) I got after disabling `hoverxref`. Here is the corresponding [log file](https://github.com/cellml/cellml-specification/files/4484843/log.txt).

**Comment by kerimoyle** [comment]
Thanks @agarny ... I've fixed that link.  Please could you try it with the normative spec only?  That's the one which the normative prelim bit will be in that I can't see?

**Comment by agarny** [comment]
Oops, my bad. Here goes: [PDF](https://github.com/cellml/cellml-specification/files/4484966/cellml2_normative_specification.pdf) and [log](https://github.com/cellml/cellml-specification/files/4484967/log.txt).

**Comment by kerimoyle** [comment]
Gah, I still don't understand these link errors in the PDF.  They're fine in the html :( all I've changed in fefd1b2 is the display.  Any ideas ... ?

**Comment by agarny** [comment]
> Gah, I still don't understand these link errors in the PDF. They're fine in the html :( all I've changed in [fefd1b2](https://github.com/cellml/cellml-specification/commit/fefd1b29ca9cc307a0e29a98893a023db6160be8) is the display. Any ideas ... ?

That's because you updated your branch and I didn't pull things... Argh! New [PDF](https://github.com/cellml/cellml-specification/files/4485032/cellml2_normative_specification.pdf) and new (better looking) [log](https://github.com/cellml/cellml-specification/files/4485033/log.txt).

**Pull request merged**
