### PR TITLE
Remove unneeded support for hoverxref

### PR DESCRIPTION
**Pull request by agarny**
Addresses issue #276.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Is it not the thing that makes those tooltips appear?

https://pypi.org/project/sphinx-hoverxref/

https://sphinx-hoverxref.readthedocs.io/en/latest/

**Comment by MichaelClerx** [comment]
I don't mind disabling it (esp. if it's in beta, as the docs suggest), but I think @kerimoyle likes it?

**Comment by MichaelClerx** [comment]
See #192 and #240 ?

**Comment by kerimoyle** [comment]
Nooooo ... the reason it breaks our build is because of something funky we've done this week ... and it's superuseful for the informative stuff where we don't expect people to have read and digested every word of the normative spec first.

**Comment by kerimoyle** [comment]
Having said that, because our PDF will be built somewhere else, we should turn off online PDF building from the readthedocs site, and simply serve the "real" PDF via our site.  If people want to download the repo and build their own, then that's on them ...

**Comment by agarny** [comment]
Ok, fair enough. Although `src/conf.py` does/did mention "Automagically convert all :ref: blocks to show a tooltip using the hoverxref", I clearly ignored it.

I agree that it's nice to have, so we should fix the problem... somehow. Am therefore going to close this PR and the corresponding issue.

**Comment by humitos** [comment]
Just chiming in here after reading that you had some issues with sphinx-hoverxref extension. Sorry :)

> Nooooo ... the reason it breaks our build is because of something funky we've done this week ...

Probably, most of your issues with the extension should be fixed with the latest release 0.3b1, released ~1h ago.

> and it's superuseful for the informative stuff where we don't expect people to have read and digested every word of the normative spec first.

:heart_eyes: 

> Having said that, because our PDF will be built somewhere else, we should turn off online PDF building from the readthedocs site, and simply serve the "real" PDF via our site.

What's the problem that you are facing with RTD building your PDF? Was it just because of this extension? What would be the difference of building on RTD than in another place?

**Comment by MichaelClerx** [comment]
Thanks!
We just want there to be a single "official" PDF, so we're disabling PDF building on readthedocs. Not a technical issue :-)

**Pull request closed without merging**
